language: go
go:
  - 1.4.3
  - 1.5.3
  - 1.6
  - 1.7
  - tip
sudo: false
before_install: 'git fetch --unshallow'
install: 'make deps'
script: 'make test'
matrix:
  fast_finish: true
  allow_failures:
    - go: tip
    - go: 1.4.3
    - go: 1.6
    - go: 1.7
notifications:
  irc:
    channels:
      - "irc.freenode.net#mgmtconfig"
    template:
      - "%{repository} (%{commit}: %{author}): %{message}"
      - "More info : %{build_url}"
    on_success: always
    on_failure: always
    use_notice: false
    skip_join: false
  email:
    - travis-ci@shubin.ca
